### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by leguimas** [andrewshawcare/thoughtworks-email-signature-generator#14]
<img width="1667" alt="screen shot 2015-10-13 at 17 53 21" src="https://cloud.githubusercontent.com/assets/717620/10468054/502eff14-71d3-11e5-906b-b5b40ef99d6f.png">
http://gentle-reef-2837.herokuapp.com/  is returing an application error. Who do manage this application?

**Comment by andrewshawcare** [comment]
Fixed
